### ISSUE TITLE
3d Positioning

### ISSUE THREAD

**Issue by KingofGamesYami** [lupus590/CC-Hive#16]
How should we use x, y, z?  Should y or z refer to the vertical axis?  Currently, lamaedit uses y as the vertical axis because this is how minecraft itself handles it, but other APIs or programs we use may not.  If they don't, I can adapt the coordinates.

**Comment by lupus590** [comment]
Use the same as minecraft. it's easier to explain in documentation for set-up
("stand on the computer, press f3 to open debug menu, copy the x, y, z values into the computer remember to subtract one from y as the computer is below you")

**Comment by KingofGamesYami** [comment]
Will do.  For future reference, this means:

x = north / south
y = up / down
z = east / west

**Comment by lupus590** [comment]
You may want to add that in you sub-project readme.
