### ISSUE TITLE
Overwrite gps.locate or edit starNav?

### ISSUE THREAD

**Issue by KingofGamesYami** [lupus590/CC-Hive#18]
starNav uses gps.locate to find it's position, should I change it to use lamaedit.getPosition or tell lamaedit to overwrite gps.locate?  Overwriting gps.locate _might_ interfere with other code, but will also allow any script to determine position while out of rednet range.

**Comment by lupus590** [comment]
What kind of things could be interfered with by having lama overwrite gps.locate? I can't think of anything that could cause problems to even poorly written programs.

The old lama had a goto function right? Perhaps you could merge starNav into that.

**Comment by KingofGamesYami** [comment]
Well, suppose a program wants to use gps.locate with different coordinates than we use.  Kind of unlikely, but...  Yeah.

The problem is, starNav isn't just a goto program.  It also keeps track of everything around it.  So I'm not going to be merging starNav into anything, just making it work.

For now, I'm going to make lamaedit overwrite gps.locate.

**Comment by lupus590** [comment]
If people use z for up (the most common incomparability we will have) then they will break lama. Also, a good overwrite function keeps the same parameters and return values of the original function (Lua does allow you to add extra on the end though).

Keep starNav as separate for now, I did think that merging the two would be a big task.

I should be doing Uni work (I'm actually behind on assignments). I will be able to help development of Hive a bit more in about 3 weeks.

**Comment by lupus590** [comment]
This issue is a bit old now, and I think solved.
