### ISSUE TITLE
Component based pre-releases (should we allow people to try the new lama?)

### ISSUE THREAD

**Issue by lupus590** [lupus590/CC-Hive#21]
The lama rewrite is complete, are you happy to have it released early to allow people to get used to it and find bugs. Also, should we continue with this release model for the other API's that we may write?
A separate installer is probably a good idea.

**Comment by KingofGamesYami** [comment]
Sure, why not?  Also - we could make it an argument for the installer, instead of creating multiple.  [My pastebin installer](http://pastebin.com/vyBeH8ZV) is basically just calling installer.lua off the github repo.  Feel free to edit, it's pretty self-explanatory and short as code goes.

**Comment by lupus590** [comment]
Do you mind if I rename lamaedit to lama? You can add in the readme that it is a rewrite of the original (with maybe a link to the originals thread/github)

**Comment by KingofGamesYami** [comment]
No, not at all.  Name it whatever you want: I named it something else to separate it from the original lama, which I was reading to understand how it worked.

**Comment by lupus590** [comment]
I'm not sure how danny is doing the server, but my original idea had the turtles storing the task they were currently performing. The will also need to know which server they are "owned" by so they can re-connect to it when they get back in range/reboot.

**Comment by KingofGamesYami** [comment]
Lama (My rewrite) stores (the last saved) fuel level, facing, direction, x, y, z.  starNav stores a map, and I'm sure other files will come up later.

**Comment by lupus590** [comment]
I think each thing should manage it's own files. This will allow people to take our API's and use them without having to edit where it stores stuff.

**Comment by KingofGamesYami** [comment]
uh... it already does?  Line 10:

```lua
 local success, msg = pcall( func, ... )
```
The ... is/are the args.

**Comment by lupus590** [comment]
Once again, note to self: read properly.

Ok, I just need to finish with my installer, need to be quick as I have updated the forum post. (doing things in the wrong order)

**Comment by KingofGamesYami** [comment]
On the forum post you spelled my name `KingOfGamesYami`, the o is not capitalized (don't worry, I've seen much worse misspellings).

**Comment by lupus590** [comment]
I think we have drifted on the original purpose of this issue, closing.
