### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by lupus590** [lupus590/CC-Hive#23]
Should Hive sandbox the code that is running in it? This may be more important for turtles as other programs may modify the turtle API and we modify it too. This may also prevent possible problems of a previous task interfering with a new one.

**Comment by KingofGamesYami** [comment]
We can do some sandboxing, but programs will be able to break it, if they actively try to.

I can see us sandboxing changes to APIs easily enough, something along these lines:
```lua
local file = fs.open( "task", "r" ) --Obviously, task will not actually be "task"
local func, err = loadstring( file.readAll(), "task" ) --the second argument, "task" gives errors a program name
if not func then
  --err is an error message
end
setfenv( func, setmetatable({ ["shell"] = shell}, {__index=_G} ) --changes the the env will not affect our copy of _G
func()
```

**Comment by lupus590** [comment]
I'm not too bothered if people try to break the sandbox, if they are smart enough to do so, they probably are trying to do something that a sandbox is preventing them.

I more want the sandbox to prevent accidental API cross talk between tasks.

**Comment by KingofGamesYami** [comment]
While we're on the subject, is there anything you want to prevent tasks from doing?  For instance, we might want to stop them from editing our files, or something similar.  We could even prevent them from running the turtle out of fuel, by terminating them if we don't have enough fuel to get "home".

**Comment by lupus590** [comment]
We would want to prevent the turtle from getting stranded when possible, I did have the idea of if a turtle finds itself without fuel, it messages its server for help, the server can then assign another worker to carry a fuel source. I would prefer to not terminate a task if possible, but preventing the turtle from getting stranded/lost would be the priority.

As for file protection, could we sandbox files too? I know there are a few of virtual file systems (VFS) on the forums, perhaps the turtle should upload changes to this VFS to the server on task completion, that way new turtles can download the old VFS when the task repeats (useful for repeating tasks such as farm tending). The attached file data can be deleted with the task if the task is discarded after completion. This may become a necessity as the point of hive is that whichever turtle is free does the task, which may not always be the one that did the task last time. @dannysmc95 may have to make some changes to his server code to support this.

**Comment by KingofGamesYami** [comment]
The easiest way I can think of to sandbox files is very, very simple:  Make a directory, edit the fs API to direct all calls there.  Said directory then contains any files the task saves, and can be easily packed into a single file and sent to the server. 

We could use something like [this](http://www.computercraft.info/forums2/index.php?/topic/18280-cc-tar-create-and-unpack-real-tar-files-in-cc/) to package it.

**Comment by lupus590** [comment]
sound good, just need the turtle to clean out task files after uploading them, now to add this to the todo files
