### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by jaredallard** [lupus590/CC-Hive#36]
Might I suggest using a submodule (git) for ccDocker?

I can implement a PR

**Comment by lupus590** [comment]
We will need to do that for some other things too (nsh/vncd), show me how to do it with ccDocker and I'll do it with nsh/vncd.

**Comment by lupus590** [comment]
I think I've done it.

**Comment by RainbowDashDC** [comment]
Yup that should be good, now I'd recommend pulling the git repo like such; git pull <repo> --recursive :)

**Comment by lupus590** [comment]
which repo do i do on that?

**Comment by RainbowDashDC** [comment]
The entire one.

```
git pull https://github.com/lupus590/CC-Hive --recursive
```

**Comment by KingofGamesYami** [comment]
Question: How does the github api handle submoduals?  I need to know this because I'm writing the installer.

**Comment by lupus590** [comment]
I think having control over the pulling of sub modules will be more useful. I'll keep that in mind though

Go though Yami. RainbowDash, you seam to be the expert here

**Comment by RainbowDashDC** [comment]
@KingofGamesYami Github handle them? No idea, but submodules are listed in .gitmodules in a INI like form that lists the remote location, you could just take that link.

**Comment by lupus590** [comment]
in the directory (after cloning it to desktop), it act like normal.

I've explained this badly, let me make an image

**Comment by KingofGamesYami** [comment]
I think I've figured it out, though it is handled differently.  
Currently, my installer gets to this part and then would fail:
https://api.github.com/repos/lupus590/CC-Hive/contents/src/Shared/ccDocker

...because 'type' is submodual.

I'm not sure what to do beyond this point at the moment. I'll keep looking.

**Comment by lupus590** [comment]
this didn't work
``` git pull https://github.com/lupus590/CC-Hive --recursive```

**Comment by lupus590** [comment]
@KingofGamesYami, you may want to check that your new installer can handle nested submodules.
Lyqyd recently changed his net-shell (nsh) repo to not include framebuffer (for I put a sub module in it).

**Comment by KingofGamesYami** [comment]
I'm not sure I _can_ support submoduals.  I'm not having any success in getting the repo URL from the submodual URL.

**Comment by lupus590** [comment]
Do you want "sub installers"? Lua files which the installer will run when it finds them in a folder it has downloaded?

**Comment by lupus590** [comment]
This may be very helpful.
https://github.com/lupus590/CC-Hive/blob/master/.gitmodules

**Comment by KingofGamesYami** [comment]
Oh yes, I can use that.

**Comment by lupus590** [comment]
A word of warning, there is a .gitmodules file inside one of the sub modules (nsh).

**Comment by KingofGamesYami** [comment]
Amazing.  I'll get to re-writing the installer soon™
